sonar.projectKey=Lau16-bit_tp-calidad
sonar.organization=lau16-bit
sonar.projectName=tp-calidad
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/test_*.py,features/**
