name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest  # CAMBIÉ a ubuntu (más rápido que windows)
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@c435f575f77fb7b3c8acf5b200f32fc115c6d03c
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
